# Whenever a tag push matching pattern "v*" then run the job
name: cloudbuild

on: 
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: Decrypt And Fix Game
      run: |
        # unzip -P "${GDC_PASSWORD}" src.zip
        sudo apt-get install p7zip -y
        mkdir project
        7z x -y src.zip -p${GDC_PASSWORD} -o./project/ || 7z x -y src.zip -p123456 -o./project/ || 7z x -y src.zip -o./project/ || unzip -P "${GDC_PASSWORD}" src.zip
        wget https://gist.githubusercontent.com/Genouka/688a29bd88e3fa711650d9b30a2fb373/raw/20952121b0707775dea1698128e976ee074d043f/GodotAndroidBuildFix.sh
        chmod +x GodotAndroidBuildFix.sh
        bash GodotAndroidBuildFix.sh
      env:
        GDC_PASSWORD: ${{ secrets.GDC_PASSWORD }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Export Game
      id: export
      # Use latest version (see releases for all versions)
      uses: Genouka/godot-export@v1
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_export_templates.tpz
        relative_project_path: ./project/
        archive_output: true
    - name: Encrypt Game
      run: |
        #zip -P "${GDC_PASSWORD}" dest.zip "${path}"
        7z a -tzip /home/runner/dest.zip /home/runner/.local/share/godot/archives/ -p${GDC_PASSWORD}
      env:
        GDC_PASSWORD: ${{ secrets.GDC_PASSWORD }}
        path: ${{ steps.export.outputs.archive_directory }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        path: /home/runner/dest.zip
        name: dest
